import { Link, useLocation } from "react-router-dom";

interface ResultState {
  predictedPrice?: number;
}

export default function ResultPage() {
  const location = useLocation();

  const state = location.state as ResultState | null;
  const predictedPrice = state?.predictedPrice;

  if (typeof predictedPrice !== "number") {
    return (
      <main className="page">
        <div className="card result-card">
          <p className="eyebrow">Prediction Result</p>

          <div className="result-icon result-icon-error">
            !
          </div>

          <h1>No Prediction Found</h1>

          <p className="result-description">
            Please submit the prediction form first to get an estimated
            property price.
          </p>

          <Link className="primary result-action" to="/">
            Back to Prediction Form
          </Link>
        </div>
      </main>
    );
  }

  const formattedPrice = predictedPrice.toLocaleString("en-IN", {
    maximumFractionDigits: 0,
  });

  return (
    <main className="page">
      <div className="card result-card">
        <p className="eyebrow">Prediction Result</p>

        <div className="result-icon result-icon-success">
          ✓
        </div>

        <h1>Estimated House Price</h1>

        <p className="result-description">
          Based on the property details you provided, our machine learning
          model estimates the following price.
        </p>

        <div className="price-label">ESTIMATED VALUE</div>

       <div className="price" dir="ltr">
          ₹ {formattedPrice}
        </div>

        <p className="result-note">
          This is an estimated market value generated by the ML model.
        </p>

        <Link className="primary result-action" to="/">
          Predict Another Property
        </Link>
      </div>
    </main>
  );
}